apiVersion: v1
kind: ConfigMap
metadata:
  name: cartservice
data:
  PORT: "7070"
  REDIS_ADDR: "redis:6379"
  ASPNETCORE_HTTP_PORTS: "7070"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cartservice
  labels:
    app: cartservice
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cartservice
      project: hipstershop
      tier: app
  template:
    metadata:
      labels:
        app: cartservice
        project: hipstershop
        tier: app
    spec:
      containers:
        - name: cart
          image: srikanthhg/cartservice:v1
          ports:
          - containerPort: 7070
          envFrom:
          - configMapRef:
              name: cartservice
          resources:
            requests:
              cpu: 200m
              memory: 64Mi
            limits:
              cpu: 300m
              memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: cartservice
spec:
  type: ClusterIP # by default ClusterIP
  selector:
    app: cartservice
    project: hipstershop
    tier: app
  ports:
  - protocol: TCP
    port: 7070 #service-port
    targetPort: 7070 #container-port